### ISSUE TITLE
"Delete Avatar" button is always active

### ISSUE THREAD

**Issue by Edik-Apoyan** [hoory-com/hoory-board#19]
### Describe the bug

On the Profile page "Delete Avatar" button is always active, even though there isn’t Avatar image

### To Reproduce

1. Log in to Admin page
2. Navigate to the Settings -> Profile page
3. Click on "Delete Avatar" button

### Expected behavior

When the User doesn’t have avatar, "Delete Avatar" button should be disabled

### Environment

app.hoory.com

### Platform

None

### Operating system

IOS

### Browser and version

Chrome 112

**Comment by god-of-javascript** [comment]
Not an issue
